apiVersion: webapp.com.tomludwig/v1
kind: Guestbook
metadata:
  labels:
    app.kubernetes.io/name: operator-scaling-package-example
    app.kubernetes.io/managed-by: kustomize
  name: guestbook-sample
spec:
  foo: bar
